### ISSUE TITLE
example docker-compose can't connect to the mysql DB

### ISSUE THREAD

**Issue by tmeulensteen** [logzio/apollo#114]
When using the docker-compose from the /exampes/ folder.
The connection to the DB can not be made.

`74) An exception was caught and reported. Message:
apollo_1  | Unable to obtain Jdbc connection from DataSource (jdbc:mysql://db:3306/apollo?createDatabaseIfNotExist=true) for user 'root': Could not create connection to database server.
apollo_1  | -----------------------------------------------------------------------------------------------------------------------------------------------------------------------------
apollo_1  | SQL State  : 08001
apollo_1  | Error Code : 0
apollo_1  | Message    : Could not create connection to database server.
apollo_1  |
apollo_1  |   at com.google.inject.internal.InjectorShell$Builder.build(InjectorShell.java:138)
apollo_1  |
apollo_1  | 74 errors
apollo_1  | 	at com.google.inject.internal.Errors.throwCreationExceptionIfErrorsExist(Errors.java:470)
apollo_1  | 	at com.google.inject.internal.InternalInjectorCreator.initializeStatically(InternalInjectorCreator.java:155)
apollo_1  | 	at com.google.inject.internal.InternalInjectorCreator.build(InternalInjectorCreator.java:107)
apollo_1  | 	at com.google.inject.internal.InjectorImpl.createChildInjector(InjectorImpl.java:232)
apollo_1  | 	at com.netflix.governator.guice.LifecycleInjector.createChildInjector(LifecycleInjector.java:331)
apollo_1  | 	at com.netflix.governator.guice.LifecycleInjector.createInjector(LifecycleInjector.java:411)
apollo_1  | 	at com.netflix.governator.guice.LifecycleInjector.createInjector(LifecycleInjector.java:352)
apollo_1  | 	at io.logz.apollo.ApolloApplication.start(ApolloApplication.java:38)
apollo_1  | 	... 1 common frames omitted
apollo_1  | Caused by: org.flywaydb.core.internal.dbsupport.FlywaySqlException:
apollo_1  | Unable to obtain Jdbc connection from DataSource (jdbc:mysql://db:3306/apollo?createDatabaseIfNotExist=true) for user 'root': Could not create connection to database server.
apollo_1  | -----------------------------------------------------------------------------------------------------------------------------------------------------------------------------
apollo_1  | SQL State  : 08001
apollo_1  | Error Code : 0
apollo_1  | Message    : Could not create connection to database server.
apollo_1  |
apollo_1  | 	at org.flywaydb.core.internal.util.jdbc.DriverDataSource.getConnectionFromDriver(DriverDataSource.java:419)
apollo_1  | 	at org.flywaydb.core.internal.util.jdbc.DriverDataSource.getConnection(DriverDataSource.java:381)
apollo_1  | 	at org.flywaydb.core.internal.util.jdbc.JdbcUtils.openConnection(JdbcUtils.java:51)
apollo_1  | 	at org.flywaydb.core.Flyway.execute(Flyway.java:1418)
apollo_1  | 	at org.flywaydb.core.Flyway.migrate(Flyway.java:971)
apollo_1  | 	at io.logz.apollo.di.ApolloMyBatisModule.migrateDatabase(ApolloMyBatisModule.java:81)
apollo_1  | 	at io.logz.apollo.di.ApolloMyBatisModule.initialize(ApolloMyBatisModule.java:40)
apollo_1  | 	at org.mybatis.guice.MyBatisModule.internalConfigure(MyBatisModule.java:134)
apollo_1  | 	at org.mybatis.guice.AbstractMyBatisModule.configure(AbstractMyBatisModule.java:66)
apollo_1  | 	at com.google.inject.AbstractModule.configure(AbstractModule.java:62)
apollo_1  | 	at com.google.inject.spi.Elements$RecordingBinder.install(Elements.java:340)
apollo_1  | 	at com.google.inject.spi.Elements.getElements(Elements.java:110)
apollo_1  | 	at com.google.inject.internal.InjectorShell$Builder.build(InjectorShell.java:138)
apollo_1  | 	at com.google.inject.internal.InternalInjectorCreator.build(InternalInjectorCreator.java:104)
apollo_1  | 	... 6 common frames omitted`

**Comment by roiravhon** [comment]
Hey @tmeulensteen, thanks!
Can you verify that you cloned the entire repo, and that apollo.conf was copied into the container?

**Comment by tmeulensteen** [comment]
Hi @roiravhon 

Thanks for your time. The entire repo is copied, content of the /root/apollo.conf is available

`docker exec -it examples_apollo_1 bash
bash-4.3# cat /root/apollo.conf
apollo {
  db {
    port = 3306
    host = "db"
    user = "root"
    password = "localpw"
    schema = "apollo"
  }

  api {
    listen = "0.0.0.0"
    port = 8081
    secret = "SECRETCHANGEMEINPROD"
  }

  kubernetes {
    monitoringFrequencySeconds = 5
    healthFrequencySeconds = 60
  }

  scm {
    githubLogin = ""
    githubOauthToken = ""
  }

  websocket {
    port = 8082
    idleTimeoutSeconds = 300
  }
}`

**Comment by roiravhon** [comment]
Hey @tmeulensteen, i think i found the issue - we neglected to specify the mysql version in the compose file - now its fixed.
Please pull the repo and try again.

Waiting for your update!

**Comment by tmeulensteen** [comment]
Pulled the new repo. New pull, new error :-(

`apollo_1  | 74) An exception was caught and reported. Message:
apollo_1  | Unable to obtain Jdbc connection from DataSource (jdbc:mysql://db.local:3306/apollo?createDatabaseIfNotExist=true) for user 'root': Communications link failure
apollo_1  |
apollo_1  | The last packet sent successfully to the server was 0 milliseconds ago. The driver has not received any packets from the server.
apollo_1  | -------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
apollo_1  | SQL State  : 08S01
apollo_1  | Error Code : 0
apollo_1  | Message    : Communications link failure
apollo_1  |
apollo_1  | The last packet sent successfully to the server was 0 milliseconds ago. The driver has not received any packets from the server.
apollo_1  |
apollo_1  |   at com.google.inject.internal.InjectorShell$Builder.build(InjectorShell.java:138)
apollo_1  |
apollo_1  | 74 errors
apollo_1  | 	at com.google.inject.internal.Errors.throwCreationExceptionIfErrorsExist(Errors.java:470)
apollo_1  | 	at com.google.inject.internal.InternalInjectorCreator.initializeStatically(InternalInjectorCreator.java:155)
apollo_1  | 	at com.google.inject.internal.InternalInjectorCreator.build(InternalInjectorCreator.java:107)
apollo_1  | 	at com.google.inject.internal.InjectorImpl.createChildInjector(InjectorImpl.java:232)
apollo_1  | 	at com.netflix.governator.guice.LifecycleInjector.createChildInjector(LifecycleInjector.java:331)
apollo_1  | 	at com.netflix.governator.guice.LifecycleInjector.createInjector(LifecycleInjector.java:411)
apollo_1  | 	at com.netflix.governator.guice.LifecycleInjector.createInjector(LifecycleInjector.java:352)
apollo_1  | 	at io.logz.apollo.ApolloApplication.start(ApolloApplication.java:38)
apollo_1  | 	... 1 common frames omitted
apollo_1  | Caused by: org.flywaydb.core.internal.dbsupport.FlywaySqlException:
apollo_1  | Unable to obtain Jdbc connection from DataSource (jdbc:mysql://db.local:3306/apollo?createDatabaseIfNotExist=true) for user 'root': Communications link failure`

**Comment by roiravhon** [comment]
Apollo might start before the MySQL container, so it can fail on the first try - but should restart and boot correctly.
Can you verify that Apollo indeed trying to start again and you get this exception on the 2nd try as well?

**Comment by tmeulensteen** [comment]
patience is a virtue.. Working now.. Thx :-)

**Comment by roiravhon** [comment]
Awesome :)
Feel free to reach out should you have more questions or issues
