### ISSUE TITLE
How do I understand these code？

### ISSUE THREAD

**Issue by sunnywa** [logzio/apollo#272]
hi,Maintainers
I wonder what design patterns the code uses. I am not understand the code structure.who can help me ?
thanks very much.

**Comment by roiravhon** [comment]
Hi @sunnywa, have you checked our Wiki? https://github.com/logzio/apollo/wiki
If you have any specific questions I'll be happy to answer.

**Comment by sunnywa** [comment]
Hi @roiravhon ,thank you first.I've read the wiki.I has another question.
in the backend code, what is the meaning of the KubernetesHandler.java，KubernetesHandlerStore.java,ApolloToKubernetesStore.java, ApolloToKubernetes.java

**Comment by roiravhon** [comment]
Hi  @sunnywa.
KubernetesHandler.java  is the class responsible for kubernetes operations. All communication with the kubernetes cluster happens in this class.
ApolloToKubernetes.java is responsible to translate between Apollo terminology and Kubernetes one, i.e. translate objects and manipulating them.

Both stores is used to Factory the classes for better and faster operations

**Comment by sunnywa** [comment]
@roiravhon ok, thanks very much.
