### ISSUE TITLE
'Getting Started with Apollo' not working due to missing image

### ISSUE THREAD

**Issue by alex-hempel** [logzio/apollo#83]
The steps described in https://github.com/logzio/apollo/wiki/Getting-Started-with-Apollo don't work because the docker-compose.yml references an image tag that doesn't exist.

docker-compose.yml:

```apollo:
    image: logzio/apollo:e4b1c1b19532be6dc7013cd4903e4a605a952edb
```

Result after running `docker-compose up -d`:

```reating network "examples_apollonet" with the default driver
Pulling apollo (logzio/apollo:e4b1c1b19532be6dc7013cd4903e4a605a952edb)...
ERROR: manifest for logzio/apollo:e4b1c1b19532be6dc7013cd4903e4a605a952edb not found
```

It appears the current image tag is 204f92d50d3d471cb24d629751c5292e14e5dbd1.

Should there be a 'latest' tag?

**Comment by ofer-velich** [comment]
"latest" tag should be available now. 
The examples been updated.

**Comment by alex-hempel** [comment]
Thank you.
